# -*- coding: utf-8 -*-
"""Factorial_via_iteration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YlICehSgX_LhAvky4AahrW0HKcTSU-vW
"""

def factI(n):
    result = 1
    while n > 1:
        result = result * n
        n -= 1
    return result

factI(4)